### ISSUE TITLE
server driven ui 적용

### ISSUE THREAD

**Issue by hye-on** [hye-on/Rails_Practice#4]
## 작업 개요
banned-words를 관리하는 어드민 페이지에 server-driven UI를 적용하여 UI 구성과 관리의 유연성을 확보합니다. 
서버에서 제공하는 DSL을 통해 금지 단어 생성 및 관리 인터페이스를 Vue로 동적 렌더링합니다.

## 작업 상세
Server-driven UI 아키텍처 적용: 서버에서 UI 스키마를 JSON으로 전달받아 Vue에서 구성 요소를 동적으로 생성합니다. 
이를 통해 금지 단어 생성 및 관리 시 UI 요소의 추가/수정을 서버에서 직접 관리할 수 있게 하여, 프론트엔드 배포 없이도 UI 구성을 유연하게 변경할 수 있습니다.
다.

## To-do

- [x]  금지 단어 생성 view
- [ ] 금지 단어 수정 view
- [ ] 금지 단어 삭제  view
- [x] 금지 단어 list view

**Comment by hye-on** [comment]
- 금지 단어 생성 view
    -  `banned-words/ui-schema`  엔드포인트에서 DSL을 반환
<img src="https://github.com/user-attachments/assets/a547ce8f-8435-4d87-91b1-a48d27177a25" width="300">
<img src="https://github.com/user-attachments/assets/8410d893-a0e5-4034-809f-d6c74fef2106" width="400">

**Comment by hye-on** [comment]
- 금지 단어 list view
    - banned-words/ui-schema/list에서 엔드포인트에서 DSL을 반환
    - banned-words/index-json 에서 entity반환

![스크린샷 2024-11-12 153614](https://github.com/user-attachments/assets/3569a04d-06e0-4e0e-bf95-76ae86e92280)
